version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  go-captcha-service:
    build: .
    ports:
      - "8099:8080"
      - "50051:50051"
    depends_on:
      - redis
    volumes:
      - ./config.json:/app/config.json
      - ./gocaptcha.json:/app/gocaptcha.json